# Generated by Django 3.1.3 on 2022-11-26 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0056_quizid'),
        ('app_mycourses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_content.quizid'),
        ),
    ]
