# Generated by Django 3.1.3 on 2020-12-18 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mycourses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject_purchased',
        ),
    ]
