# Generated by Django 3.1.3 on 2022-11-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0056_quizid'),
        ('app_mycourses', '0002_quizresult_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='counter',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_content.quizquestion'),
        ),
    ]
