# Generated by Django 3.1.3 on 2022-05-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='background',
        ),
        migrations.RemoveField(
            model_name='author',
            name='photo',
        ),
    ]
