# Generated by Django 3.1.3 on 2022-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_auto_20220512_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='background',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
