# Generated by Django 3.1.3 on 2021-05-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='subject',
        ),
    ]
