# Generated by Django 3.1.3 on 2021-04-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapter',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='chapter',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
    ]
