# Generated by Django 3.1.3 on 2021-05-26 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0002_remove_answer_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_content.mainsubject'),
        ),
    ]
