# Generated by Django 3.1.3 on 2021-04-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0002_auto_20210404_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='subject',
            new_name='course',
        ),
    ]
