# Generated by Django 3.1.3 on 2020-12-05 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0002_bestseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_content.mainsubject'),
        ),
    ]
