# Generated by Django 3.1.3 on 2020-12-05 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0003_auto_20201205_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('quntity', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_content.mainsubject')),
            ],
        ),
    ]
