# Generated by Django 3.1.3 on 2020-12-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0004_averagerating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='averagerating',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
