# Generated by Django 3.1.3 on 2021-05-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0004_auto_20210526_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsubject',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
