# Generated by Django 3.1.3 on 2022-05-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0005_mainsubject_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(null=True, upload_to='https://selfcare.cdnnow.ru/projects/5d5744fd-8dff-458c-949f-6fd1445f9b49/vod/videos'),
        ),
    ]
