# Generated by Django 3.1.3 on 2021-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0005_auto_20210406_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='subtitle_file',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='translation_file_1',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='translation_file_2',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='translation_file_3',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
