# Generated by Django 3.1.3 on 2021-04-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0006_auto_20210412_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='translation_file_1',
            new_name='translation_file',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='translation_file_2',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='translation_file_3',
        ),
    ]
