# Generated by Django 3.1.3 on 2020-12-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0007_auto_20201210_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagerating',
            name='rating_averge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
