# Generated by Django 3.1.3 on 2020-12-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0008_auto_20201210_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagerating',
            name='rating_averge',
        ),
    ]
