# Generated by Django 3.1.3 on 2022-05-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0008_auto_20220514_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
