# Generated by Django 3.1.3 on 2020-12-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0009_remove_averagerating_rating_averge'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagerating',
            name='average_sample',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
