# Generated by Django 3.1.3 on 2022-05-14 14:45

import app_content.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0009_auto_20220514_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(null=True, storage=app_content.storage.OverwriteStorage(), upload_to='uploads'),
        ),
    ]
