# Generated by Django 3.1.3 on 2020-12-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0010_averagerating_average_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='averagerating',
            old_name='average_sample',
            new_name='average_rating',
        ),
    ]
