# Generated by Django 3.1.3 on 2022-08-16 12:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0011_auto_20220514_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='lecture',
            name='dash_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='fairplay_certificate_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='fairplay_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='hls_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='widevine_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='playready_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='processing_state',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
