# Generated by Django 3.1.3 on 2020-12-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0011_auto_20201210_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagerating',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='averagerating',
            name='av_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
