# Generated by Django 3.1.3 on 2022-08-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0012_lecture_video_file_link_squashed_0018_auto_20220812_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='price',
            name='regular',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
