# Generated by Django 3.1.3 on 2020-12-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0012_auto_20201210_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubject',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
