# Generated by Django 3.1.3 on 2022-09-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0013_auto_20220829_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='money_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
