# Generated by Django 3.1.3 on 2020-12-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0015_auto_20201218_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubject',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mainsubject',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
