# Generated by Django 3.1.3 on 2022-09-04 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0003_auto_20220512_1957'),
        ('app_content', '0015_transaction_date_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_accounts.author'),
        ),
    ]
