# Generated by Django 3.1.3 on 2020-12-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0016_auto_20201218_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsubject',
            name='transactions',
            field=models.IntegerField(default=0),
        ),
    ]
