# Generated by Django 3.1.3 on 2022-09-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0016_transaction_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
