# Generated by Django 3.1.3 on 2022-09-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0017_transaction_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_bought',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_paid',
            field=models.DateField(null=True),
        ),
    ]
