# Generated by Django 3.1.3 on 2020-12-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0017_mainsubject_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_content.mainsubject'),
        ),
        migrations.DeleteModel(
            name='Bestseller',
        ),
    ]
