# Generated by Django 3.1.3 on 2022-09-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0018_auto_20220912_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transferred_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_transfer',
            field=models.DateField(null=True),
        ),
    ]
