# Generated by Django 3.1.3 on 2020-12-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0019_auto_20201219_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='AverageRating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
