# Generated by Django 3.1.3 on 2022-09-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0019_auto_20220914_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='money_paid',
            field=models.BooleanField(default=False),
        ),
    ]
