# Generated by Django 3.1.3 on 2022-09-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0020_transaction_money_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='enumerator',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='enumerator',
            field=models.IntegerField(null=True),
        ),
    ]
