# Generated by Django 3.1.3 on 2021-01-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0022_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='thumbnail_file',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
