# Generated by Django 3.1.3 on 2021-01-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0023_lecture_thumbnail_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='thumbnail_file',
        ),
    ]
