# Generated by Django 3.1.3 on 2022-09-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0025_auto_20220923_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_content.mainsubject'),
        ),
    ]
