# Generated by Django 3.1.3 on 2021-01-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0026_auto_20210104_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsubject',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainsubject',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
