# Generated by Django 3.1.3 on 2022-10-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0026_auto_20220923_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalMaterialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lecture', models.URLField(null=True)),
            ],
        ),
    ]
