# Generated by Django 3.1.3 on 2022-10-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0027_additionalmateriallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalmateriallink',
            name='title',
        ),
        migrations.AddField(
            model_name='additionalmateriallink',
            name='url_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='additionalmateriallink',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_content.lecture'),
        ),
    ]
