# Generated by Django 3.1.3 on 2021-01-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0027_auto_20210105_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mainsubject',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
