# Generated by Django 3.1.3 on 2021-01-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0028_auto_20210105_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badword', models.CharField(max_length=50)),
            ],
        ),
    ]
