# Generated by Django 3.1.3 on 2022-10-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0028_auto_20221006_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalmateriallink',
            name='additional_file',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
