# Generated by Django 3.1.3 on 2022-10-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0029_additionalmateriallink_additional_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmateriallink',
            name='additional_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='AdditionalMaterialFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_file', models.FileField(null=True, upload_to='uploads/')),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_content.lecture')),
            ],
        ),
    ]
