# Generated by Django 3.1.3 on 2021-01-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0029_badword'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsubject',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
