# Generated by Django 3.1.3 on 2021-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0030_mainsubject_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
