# Generated by Django 4.1 on 2022-10-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0031_remove_additionalmateriallink_additional_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='size_mb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
