# Generated by Django 3.1.3 on 2021-01-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0031_lecture_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
