# Generated by Django 3.1.3 on 2022-10-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0032_auto_20221012_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
