# Generated by Django 4.1 on 2022-10-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0032_alter_lecture_length_alter_lecture_size_mb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubject',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
