# Generated by Django 3.1.3 on 2021-01-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0033_remove_lecture_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
