# Generated by Django 3.1.3 on 2022-10-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0033_auto_20221012_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='size_mb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
