# Generated by Django 3.1.3 on 2022-10-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0033_alter_mainsubject_length'),
        ('app_content', '0034_auto_20221014_1249'),
    ]

    operations = [
    ]
