# Generated by Django 3.1.3 on 2021-01-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0034_lecture_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
