# Generated by Django 3.1.3 on 2021-01-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0035_auto_20210110_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
