# Generated by Django 3.1.3 on 2022-10-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0035_merge_20221015_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsubject',
            name='author_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mainsubject',
            name='discount_programs',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
