# Generated by Django 3.1.3 on 2021-01-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0036_lecture_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='size',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
