# Generated by Django 3.1.3 on 2022-10-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0036_auto_20221025_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsubject',
            name='length_1',
            field=models.DurationField(null=True),
        ),
    ]
