# Generated by Django 3.1.3 on 2022-10-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0037_mainsubject_length_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='length_1',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='length_1',
            field=models.DurationField(null=True),
        ),
    ]
