# Generated by Django 3.1.3 on 2022-10-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0038_auto_20221030_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='length_2',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='mainsubject',
            name='length_2',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='length_2',
            field=models.TimeField(null=True),
        ),
    ]
