# Generated by Django 3.1.3 on 2021-01-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0040_lecture_size_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsubject',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
