# Generated by Django 3.1.3 on 2022-10-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0041_auto_20221030_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='length_2',
        ),
        migrations.RemoveField(
            model_name='mainsubject',
            name='length_2',
        ),
        migrations.RemoveField(
            model_name='section',
            name='length_2',
        ),
    ]
