# Generated by Django 3.1.3 on 2021-01-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0041_mainsubject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsubject',
            name='prerequisite',
            field=models.TextField(null=True),
        ),
    ]
