# Generated by Django 4.1 on 2022-10-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0043_auto_20221030_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubject',
            name='length',
            field=models.IntegerField(default='00:00:00'),
        ),
    ]
