# Generated by Django 3.1.3 on 2021-01-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0044_bank_account_credit_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_card',
            name='card_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
