# Generated by Django 4.1 on 2022-10-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0044_alter_mainsubject_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubject',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mainsubject',
            name='length_1',
            field=models.DurationField(default='00:00:00', null=True),
        ),
    ]
