# Generated by Django 3.1.3 on 2022-10-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0045_alter_mainsubject_length_alter_mainsubject_length_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='translation_file',
            field=models.FileField(default=None, null=True, upload_to='uploads'),
        ),
    ]
