# Generated by Django 3.1.3 on 2021-01-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0045_credit_card_card_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_card_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
