# Generated by Django 3.1.3 on 2022-10-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0046_auto_20221030_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='translation_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
