# Generated by Django 3.1.3 on 2021-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0046_credit_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credit_card',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paypal',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
