# Generated by Django 3.1.3 on 2022-10-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0047_auto_20221030_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
