# Generated by Django 3.1.3 on 2021-02-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0048_pref_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_card',
            name='ready',
        ),
        migrations.RemoveField(
            model_name='paypal',
            name='ready',
        ),
    ]
