# Generated by Django 3.1.3 on 2021-02-07 08:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_content', '0049_auto_20210206_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pref_payment_method',
            new_name='Main_method',
        ),
    ]
