# Generated by Django 3.1.3 on 2022-11-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0050_quiz_quizanswer_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(null=True, upload_to='uploads')),
            ],
        ),
        migrations.RenameField(
            model_name='quizanswer',
            old_name='blocked',
            new_name='correct',
        ),
    ]
