# Generated by Django 3.1.3 on 2021-02-28 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0054_auto_20210228_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubject',
            name='date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
