# Generated by Django 3.1.3 on 2022-11-26 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0054_auto_20221124_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_content.lecture'),
        ),
    ]
