# Generated by Django 3.1.3 on 2021-02-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0055_auto_20210228_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubject',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
