# Generated by Django 3.1.3 on 2022-11-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0055_quizanswer_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
