# Generated by Django 3.1.3 on 2022-12-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0056_quizid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsubject',
            name='being_edited',
            field=models.BooleanField(default=False),
        ),
    ]
