# Generated by Django 3.1.3 on 2022-12-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0057_mainsubject_being_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
