# Generated by Django 3.1.3 on 2022-12-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0058_lecture_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsubject',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
