# Generated by Django 3.1.3 on 2021-03-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0058_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_account',
            old_name='first_name',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='bank_account',
            name='last_name',
        ),
        migrations.AddField(
            model_name='bank_account',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bank_account',
            name='entity_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bank_account',
            name='itin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='bin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
