# Generated by Django 3.1.3 on 2022-12-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0059_mainsubject_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
