# Generated by Django 3.1.3 on 2022-12-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0060_section_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
