# Generated by Django 3.1.3 on 2021-01-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='video',
            new_name='subject',
        ),
    ]
