# Generated by Django 3.1.3 on 2021-01-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0003_auto_20210107_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
