# Generated by Django 3.1.3 on 2021-01-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0004_auto_20210107_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
