# Generated by Django 3.1.3 on 2021-03-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_workshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='country',
        ),
    ]
